name: Seek Disruption
favicon: null
layout_spectrum: 0.34218551660887897
typography_spectrum: 0.7174868315923959
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.32201175135560334
  lightness: 0.9696496471296996
  saturation: 0.6078127375803888
  rhythmicContrast: 0.9610679775942117
purpose: []
